### ISSUE TITLE
Possibility of providing the `WinMetadata` during build?

### ISSUE THREAD

**Issue by mainrs** [mrshmllow/affinity-nix#1]
I am not sure if it is possible to put the file into store without pinning it with a hash to be honest. What I imagined was that one can zip their windows folder and put it into the store. And the flake can detect it and run the copy itself.

On a side note: do you happen to know if it is possible to run Affinity V1 on Linux? I didn't manage two years ago because a lot of Wine functions were missing.

**Comment by mrshmllow** [comment]
I also wonder if it's possible to use a donor WinMetadata folder for everyone. Im guessing affinity uses it for some kind of fingerprinting? I have no idea what's in that folder anyway and can barely get information online

**Comment by mrshmllow** [comment]
I have never used affinity v1 but I may look into it

**Comment by itslychee** [comment]
you can use `requireFile`

**Comment by mainrs** [comment]
> I also wonder if it's possible to use a donor WinMetadata folder for everyone. Im guessing affinity uses it for some kind of fingerprinting? I have no idea what's in that folder anyway and can barely get information online

https://github.com/daniel080400/AffinityLinuxTut/blob/56e34239b347ad2c49916897ae7daf12ee404d0b/WinMetadata.zip

**Comment by mrshmllow** [comment]
> you can use requireFile

WinMetadata seems to be some stupid winAPI namespace _thing_ idk if it will retain the same hash every time

**Comment by itslychee** [comment]
> > you can use requireFile
> 
> WinMetadata seems to be some stupid winAPI namespace _thing_ idk if it will retain the same hash every time

ughh sounds obnoxious

**Comment by mrshmllow** [comment]
Just bisected system32/winmetadata and it only actually requires `Windows.Services.winmd` to launch
